spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbprova
    username: root
    password: toor
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update