spring:
  profiles:
    active: prod,h2
  graphql:
    graphiql:
      enabled: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /control
      exposure:
        include: '*'
  server:
    port: 8088